apiVersion: v1
kind: Namespace
metadata:
  name: noor-platform
  labels:
    name: noor-platform
    environment: production
    project: noor
---
apiVersion: v1
kind: Namespace
metadata:
  name: noor-monitoring
  labels:
    name: noor-monitoring
    environment: production
    project: noor
---
apiVersion: v1
kind: Namespace
metadata:
  name: noor-high-sensitivity
  labels:
    name: noor-high-sensitivity
    environment: production
    project: noor
    security: high
